### ISSUE TITLE
Repeated characters when typing tags 

### ISSUE THREAD

**Issue by Vaansilver** [perlatus/e1547#41] opened 2018-01-17 02:01 UTC
Typing in tags is a bit broken
Typing a single letter causes it to type 4 or 5

**Comment by perlatus** [comment] 2018-01-17 02:21
Are you on the latest version? It used to be really glitchy, but it should be fixed now. Latest is [0.1.9-alpha](https://github.com/perlatus/e1547/releases/tag/v0.1.9-alpha)

If it's still broken, let me know what keyboard you're using so I can try to reproduce it.

**Comment by Vaansilver** [comment] 2018-01-17 17:48
Yeah I'm on the latest version, weird
I'm using a TouchPal keyboard

**Comment by perlatus** [comment] 2018-01-17 20:39
I've got the repeated characters on one of my dev devices, but with the default samsung keyboard. TouchPal works just fine on that one though. Going to have to wait and see if anyone else is getting this since I'm not sure where to start debugging.

**Comment by perlatus** [comment] 2018-03-23 20:12
User report of this issue on Smart Keyboard Pro ver 4.21.0

**Closed** 2022-04-25 20:06 UTC
Labels: bug, wontfix
